/// <reference path="../pb_data/types.d.ts" />
// ─────────────────────────────────────────────────────────────────────────
// PAYMENTS PLUGIN — Startup bootstrap & configuration validator.
//
// This is the FIRST file executed by PocketBase on startup.
// It validates ALL required configuration (env vars + DB settings).
// If any critical config is missing, PocketBase boot is halted with
// clear instructions on how to fix the issue.
//
// DO NOT EDIT this file. To add business logic after a payment completes,
// edit: pb_hooks/my_app_clip_handler.pb.js
// ─────────────────────────────────────────────────────────────────────────

onBootstrap((e) => {
  if (typeof e.next === "function") e.next();

  // Load the config validator — runs BEFORE any other plugin logic
  const validator = require(`${__hooks}/plugin_config_validator.js`);

  // validate() throws if critical config is missing — halts PocketBase boot
  validator.validate(e.app || $app);

  // ── Success banner ─────────────────────────────────────────────────────
  const apiKey = $os.getenv("CLIP_API_KEY");
  const pbUrl  = $os.getenv("POCKETBASE_URL");

  console.log("");
  console.log("══════════════════════════════════════════════════════════");
  console.log("  PAYMENTS PLUGIN — Ready");
  console.log("══════════════════════════════════════════════════════════");
  console.log("");
  console.log("  Clip:");
  console.log("    CLIP_API_KEY     : " + (apiKey ? "✓ SET (" + apiKey.substring(0, 12) + "...)" : "✗ MISSING"));
  console.log("    POCKETBASE_URL   : " + (pbUrl  ? "✓ " + pbUrl : "✗ MISSING"));
  console.log("    Webhook endpoint : " + (pbUrl  ? pbUrl + "/api/clip/webhook?token=<secret>" : "not configured"));
  console.log("");
  console.log("  Collections : clip_orders, clip_payments");
  console.log("  Routes      : POST /api/clip/create-link");
  console.log("              : POST /api/clip/webhook");
  console.log("              : POST /api/clip/refund  (admin only)");
  console.log("");
  console.log("  SPEI:");
  console.log("  Collections : spei_settings, spei_orders, cep_verifications, spei_banks");
  console.log("  Routes      : POST /api/spei/create-order");
  console.log("              : POST /api/spei/report-payment");
  console.log("              : POST /api/spei/validate-cep");
  console.log("              : GET  /api/spei/order/{id}/status");
  console.log("");
  console.log("  Business logic handlers:");
  console.log("    → pb_hooks/my_app_clip_handler.pb.js");
  console.log("    → pb_hooks/my_app_spei_handler.pb.js");
  console.log("");
  console.log("══════════════════════════════════════════════════════════");
  console.log("");
});
